name: Build DotNet
author: Els_kom
description: 📦 GitHub action to build, test, and package projects.

inputs:
    SOLUTION_FILE_PATH:
        description: Filepath of the solution of which contains all the projects to be built, optionally tested and packed, relative to root of repository
        required: false
        default: ''
    TEST:
        description: Flag to toggle running unit tests for the projects built, disabled by default
        required: false
        default: false
    PACK:
        description: Flag to toggle packing the projects built
        required: false
        default: true

runs:
    using: node12
    main: index.js

branding:
    icon: package
    color: blue
